apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ManagedClusterSet
***REMOVED***
  name: all-openshift-clusters
  spec: {}

---

apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ManagedClusterSetBinding
***REMOVED***
  name: all-openshift-clusters
  namespace: openshift-gitops
spec:
  clusterSet: all-openshift-clusters

---

apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
***REMOVED***
  name: all-openshift-clusters
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: vendor
          operator: "In"
          values:
          - OpenShift
---


apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
***REMOVED***
  name: argo-acm-clusters
  namespace: openshift-gitops
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters
    namespace: openshift-gitops