apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: quick-start-build-env
spec:
  encryptedData:
    password: AgBiQ7jxUoPyap/tj40hFcuBJplxKWr0Vj/zezweICYjUJzHhdr2PWhHJv7bOQ8CiXBTdfbJZ9SWM5V/HZ2qx+l+rbxiW5zX22f6+b7K1ul8XE0d6LjSQOr+TOe3KUaiVMJltE+14JX/KGnjTqxxsBAM7GN7Z9RObOF8q4PHujkIkAT64FIXruAA2NDpaV0FxBl+BadQhAPa+APJ46nVfh2KCLWt6e9OWEUovwH2mgYLRJhpMoxiyQC76mMn2i34DPY/SAJYeVOJDLfbedGffWqdhGh8wMSMdcARAzs1vx7l/dm4886PKyi2yH2B7sTmapuWOIY8lmeCMniBoU81Zfa3NDmCR+4Dbj5WL8+UVyK83cN0lBN8cLRGq2kasuX9lmI7b9iTIASLxjAVU/ChDau74U1xwdlCOF7MrJ0HT4MZ8AEvt1irG2Rcv2XPiHsDneb536sEFrPX2SveTCyMxujQ3Optgp5/KBIaxPzwUICETdr5xR5DGiarHZRo3AFOTw040oB0kyhbhe8Z9gelIflZ1woiCa9lCRMT/PoXBevP0nFfIBn79QjxtvRgwdwrts+eDbmoetVvUcr/ATyifJjj2WZitQB4vGNgwqEZS1gH6fjAl7jCN2DO0tMI2tMHh8/s+qt69460LYtITOrM0cE3MuE6hvlpuLKhfHesxqX7xadpcRe7RO5dC6Y/rlZnBZta5t8JeK+QxF/oHL7BARxWvYuDnch5OwOagQJykJOyO7SjzhbTkhYZVGFjiW6SVP1axQoASse65EX7OGA/vqhPlv3JxHq731hpnnSCqzHwx1BehzRU2UVtLYFjqDY=
    username: AgCU0e23KoCVVFvw7TKp62Y0eARdgx6A7QanS2GMVNxBRkqzU77PSdr+lfOB0GTExEUmEc661p4Cw8Jnz9sIuK1bx4ZB/2fwW2sFai0c0VWjjKJzJlY01a2OBdbzmrMjsDLSRPXclQ16af/Pf+jWhYPb4RPPaCuJnxi9LOw2sDEUQ9ufLEDVrSoGimhTIZxOyIas2Vrz6Tej+mMnSrcg5uOsWa1oAVIeOdJBJhE8l95C/13VOFd7zDaXolSCcVrb+Fqvgp1j1fUh+SCLU9VTehHoJVoDzmITRyTZ5dneNhYU2zm0doDge/WABC7ATKcA2ByPJax9QlDQRnFfqInos1bw+WLNWts5pJD0Dwuv5xknj+e8vK3hL5xsiG8bQHeob01DfvqxeC0dns0yeITxYDRtSKD8Nk4GgAIP/CDdxh4oVJcxfXkCgntgz5/18RVICcIdaCkbeBJMotE1toYUjKiJJfW/qrnuMTtxyULMnMO3SLQnaFntVvnwZ3608NpQcDVkrkTdIqi+gddTJmPjhZ7OfIHASRpAScXDc8AfoM/u9qJ729oXTtIgqaHo3nXneYj+XZwoAyQze6bzli9/lJ9bDGd+xHLo3/27J9IR6mOBWC+fPxGoszNpUZchGer+Jh1SMSRmLMEamniCQgGWvFHIvkSivP9vFNi+F1m3xH0uSsz4sIUTgCtJLL/tQrqUrg+d+cTm5oA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: quick-start-build-env
    type: kubernetes.io/basic-auth

