---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: demo-tekton-build-env
spec:
  encryptedData:
    password: AgBYAgiIWXQea+u9v/ebEt/c1h6eW9w8H8wyw1k2TKk/VoCt+x7aJjjui0+viTwn65Jp2ycaVlxjtemD5cwROE7jXCsIh1j74Q6c1S/QYku6fT4NYwM5IFOZ9/RD8JJ4jkm9ug9IbJ/b6LZ1D4JIo8L5bYI/qfLY9PFJNaIF0PoW6/zgCMWTOC8b4rZtfAqFZOHF6HGj2vZl8pBSf8FcDLBi8bqRWOdW6nmK5hQIc8mLt609YzKf+MKrBJKK8jFGmDtOZDC7zDhbCEQHApbRvSqMfsSTicdhjBpXJ6R0dfGF/0x55+nXoS7qBDc3QnzBwGk/hd1ykD19NXMf9XtfszQECe6UdwbaZ/m3oGn8eIGaQOHQos8Y2eY1Jvp3Q+Zz+x5lr+W2LT+n9A/7KSStrlIJ0O/Q2PAxMsTbxRDmCOUleINN8h7nAKwrZBo6I5XiQBDFfUBOMRj6VbKJygF4XuWxd9ubTxC/dXbNV8fMM1kGoQ1zIKahOucZhZMnccLHyurb0GLqSVgY8eWaKgKLK8dmfVcMBnJqZ5do271iqiGOGkK5zu8KeLHe2wOFS7OazZoaJwk0lZK2c7GFqxTF95cfZZeZQQAuJW7iS24XpAlJ8U7Aj+pXYg3//lyyOY8DEkOzPfYJIrrfieJPFtGFgMzBhw4+EDfkNGaSRZc05bPSWGqZKJ9j3k1PR6WJYMEaCT7GL3ley1f6pFtlOe4rVfzF5S+r+dDTf/bhVP7+1Mw3hz3j/FBX1zMFG3rh4TyTc8Q/7+LmFIZdAN550xfEZ2QaTKr5KUXaRvL4FQ2BuQyz31z61NHNtIfoNSnxvBw=
    username: AgCWjzaLL+7CC1od/TM3tf2EaoInLByeSkoBO+hUfwBimaDPF3J09b5IA5Y1Tu9vBeN/U/2h3pFhA6g8K0F05I8yLH40ak39KrxebiX6Vpcc5M9y2G5lNa0cEiZA1UCT6YOnxjLpUkSIP+Rkl8NnnaE3xC+t8ZpEzY9B0ZX7JBdgGQShC1a4E+h2j8ml7LuOfK8f1TXXPP625oqHt4hsVotRphvlGhkSQ2TypxSF6Y/psLamLbo9oiViVucN40YZZvla8qguCAB8BSSlGxdFG1H5OPDr0DwuF5VdFlJcpiRjeW9vvRITXm/h+fD0MakVqPfBJWXaGYhQcyeVfOjafRSRkc/1Kjxn6Vq4ZZLEQTNpw5hfwGRUHypSXm9bcvSjTEtm7ZvbbWdIx3FQyKYLGFKXa0ZantxXCFHTX3r+2LvEamc40ndIXl7truvskVgJZTfQkfoHAo/Q0FlMFfBN2BipY4WezffrTL3hJoWIhiy1iMnBx63PEMLVftd8Cj5eBJD49mez6f45rckrEtkzJMMP3Jl70MqOFVqTHCyBAe1s/vSu8xMre8lMz3Svp25FE3ICsSfkB5O9DPCMt0nggUbxb+Y1KTCL0TkjzXS4lYq7uSA2q4WDVblvasr+vzyKluQEoHT+ejjuD81zMnX9SpQPAcllp5rvN9ABv63n5wf9jDrNe1iJ0bSyUaFGU0LhhP55ZGs7tV8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: demo-tekton-build-env
    type: kubernetes.io/basic-auth
