apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: demo-tekton-build-env
spec:
  encryptedData:
    password: AgByn5M7g9l2CzrJx7mmINEOluHGRKAZq8BABs8h3kz7NRW8BFh7Q1+x8zrWxia+4aQOhF2Vhs84JL1QDTn0yLIC/NfHOid5fO++gp8+cGLpd3+DPrbfNzshapWj84UgumF1kYMMjra0VsEzJpbQIv7uyI0CFi6nqeoSrLOxMGaYo6l1teT/zEpsmcC9RpO2AAydkrmg/+9d1x9qQOz8ms8eA4AHmSi5gNwuuv/uGSLHUAB5cxi2Bhj2SvGXEaMuwhUsl0/uY/1PxmK/UxqGVbuywZ5AyIVcNlE9FT4FyO9engJydzLH76xkBpEN9DeXTVz8t/YWgQ02e9eMIXDdJoOlzIwlEKw49iAmwiSPIQS5b/UI+3/kcF9WDBCtXHUcCFMg/9vU73nv0Lc6Mpqm1NFrrmDdHcXwn2umyDbXpo9HwtXPMjfghoAeE+vjeen/XgqkJuPsoQh4RIKNT8WLdPZBybmh99dkV3d18WpHiRSiT7hgNc4TY2DsNneQJgqTLJLzK+Vascpq4jPgDR6VK2RoBNwzIe8+6qijni10iF7aUH/pPJbhtgFVEEdqP/S0rP7VNFLghInklzf9dmdfpYFQCHD3xlD1T501/43RyJ21LirjHL2zdHpDkYMjy/JN+kYmfjkyvvYtiOEpSoQtxhJ6d9x6mLIsvHPVsASnA15TR725oTjR7dlI6BXy6syr3AwdHDPSYl0cnx4rS3PHzUjiA480GY6agzIYxeXP+SpbbTioyejmjn8JjBJGGictE75ihFyk4bqvHUkUGHl6TCn+3izP5kcowuPjqnVtzUWmCFhEQwYopP7iGejTDXg=
    username: AgA5WgM8wpMaTrNlaC01WvmXZd80VSpdy0krS5R6kFpD1EBq/AKPJX5/pKRllyjVFngvOcZ7aV3FKGp29e3GV+9x4rWmfEwyU7wYhNni/cg14x5+2YomQ3/UcvEtLQeLHxOZEb9PpPuVp4aJhs/UjXorQYDrlsYKA6eusdO1/GHh07lHuOymFXxBJuDI8qbKi2MQKWFcStAbFBFJo2gBmaRQWnqxlnvSsp548D1TswuAjb4RMj2jZNuWu1LZnmTGxwgDr7mGdH+D8S2lPFKNKpgCtfA6JrT+0bCxcah52/KyI/f/gqNivYvSCpSDMoOMMyZ23vxMdfhqjbC01DSBQx++kAF6T3VvIKOSWIcWXDBB18mnK56TfGLxQmoY6F0z8Lio3DdellXWjKujsMB6CK+DijEahB1jJ4nAHCii+GgNA3o2HfjXrcFhV2pvRjpaGWEWdmJaE42n9JnQPYN42OWQBoYvfqYado2GvqzhMUmXx+qPrxGMpyot9GZ5pmLtrUWW0fNi1/M3GdnrqUOt1nzobRcLJPuYDazL1eCzgYPiJlS/OsLqwkGAgIfP/j2rZ18dUL3NcOjG2HCdjmDJXxO5+0F/jKlOE7bWfgdHiEJqKtt5F5ZXVVA2wB9xyUXcguiUHrbdpP9RzpZGVWnS+TXzFbAojotng346nAl7+uqj1IQZ7n10H8X/kFMafzuIVV4ykOzV/40=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: demo-tekton-build-env
    type: kubernetes.io/basic-auth

