apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: quick-start-build-env
spec:
  encryptedData:
    password: AgB7fv+4QAOxWfB5gPm67A/AUKCNCe4HppMSaFTpm/sa7jUnidGNal9j/GJVAueb/Y1CUCXzUaE5uuvjUf1CqIegrrjgyB7jDnFLmM66VoVig36BQv5aM7xmamWmVGjCetNEBaq0MgY7LPGBQYj37vVWPsrfBQvzMaCHihEyovo4X/waq91kNSXIsHvgPKTfKoNBPFsK5DVIecVIZjd9DLzh2OCtDL48ICierVlUzclGepu6nw8UbqC+m+ZQnXbWChHJUqcQz4dPDJMJKvLO/iCz48T7rpVatjp8BbtiforqFah+IqaJxfgWSsGRE3Zk0tARDcf4z6s+rGEg4yHW8bax/ICYH8YSF7ARZJB4pVt++vjKzITOvk0FjW1sTlT8ob21iUp2rbJ7QIjbhVwaeOJeHovTwd32+xHqb9FplMOZlGseMZTAIStIN6qW41TmMpANvgzKQtSru03eb/G7al3EEqx9guxLeG9HYqe64Ct1RYe4sq06Io+veQVnVSm87/ft7ynGQ8DELvuQTQf2inkApXOL3XTpfAxFqmwez+fMjbAbd+CvCyv5diPi2UZRW6upAuczmtTnKA4wZYanvgNWeyqZ0ERD+TlT9f58J8fSg6i4Lbpo92rInQ7pNbouRJrb9DSGPG7NeEg5XQO0alX/huogpm+4gycKM+FQfaLtDjqm/q7TtYu7+ds9KmH8FUVHUZD0krJISGXM/4jwEp0xusrLIv4mWg6v7lhp3wIi48rXBH6hAWq/BH1zAVF46XivsicO3hcg3ygbSNilAcpDBorH6G/F4NPwvCWgf4SZRT/XPXPiKwfV23e2Ppg=
    username: AgAFaNMRa1U80DPZFz97umON3omgIsgqfo2lJNrBDfh0eGH5vOYcyvTH4gAWLukUVOIGffcvb6ETs1HTS85W0wqA4spFxBRkLjYgXHHDKwVLjFc2Nlw75EKASRLYtcCbL+bXDb+2TwgYcY5oqyp+ldPexhrw6FdRiCc2vujJSxLgQQqKpv1q1WtVZBTYt1+tCwAZ7+KC9+7H3viedqHsEExJxM2esy+VDzDRVpUCmy9g0XkbqrZdd0ARFmsT3vlaCWkzB5HlbaBv6QnnqcCOjOkeyx+YLpw268cs+TUKPj27kzjp2c+yHxPoRntYXD88dFN1dDupTwP1VVeALO3WrUM50LWeBegm7z/jcBvqG3EvtA9mddiCJmnN+3k6wBaxAXoN5DlNRQ15NresO06ySx16RYR5PIXxFkhiowbfCN0oRZxVG8K1sLfjSQge+a6gbVuKczTQPbk93xOZ/hUzGbWvwB+pIpOtGMvN7vnUoZ6QMx7ir9/IgszlMs/00E3N8rrzbAaLifKuxp+ikUnHCnGgY8vvZtVxCBUBL0lGchkmsqWuImGjwrQwbzhfUL0KMsJ5n9EV8Pbw/UZNIm698XxXExmGoHc11XaJ/9Efs8F0qsCKEVjj5hQ+yyyRBckCKu5+QmiFH+5zBAGSpEfLHk+2mPHflUrPujPymrB4wcylZTdNPsYDBsIpo4iJse1qpKfoC+/Jqm4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: quick-start-build-env
    type: kubernetes.io/basic-auth

