apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: quick-start-build-env
spec:
  encryptedData:
    password: AgBHnnMTe2HiV19FA4mC7EBTnCYfdDYUdOiOOAD2oiSYDtwTYmgx8QHoyLbUwaG8XVFBBomcM2JPZuphn5+1kwYP8X8/+yFZ7sR4Aahs2kg3KzmP8LPS38BCCUmf54Kbn2Lyn9VTmoATw6o+cm+hqt9YoyQi5HyVvc5oVKazhQuqZeRHqcDGP9LzF9ozW8TIuNIO9UggAwolJ4XDOhdGckl7PPO7r5djcvjB4lThKjG3MFdDcQfUKp1atAT5ikMEcOp+7+p7MxUdZbReIHqxWiGmNOM1Gav5f3tx8TxC5SYS4xYRJQEpkeHA/30uMKPRikrEZaRvLFHCKox97AORmgYQOkVoRXmynLd1DZDcYhioZVRoHlWC/mDppIrwgoTxT4b9oPo7cqpVV0tcK2bDfGrOXwCDLgVys0CkJl6Ij9UoJZi8WXpD4Am/wZNu8dFgCOoWrNMkpG0ffsKUbnnNqa3Rv2i/EQMXvP5uiGS5y/yTURE+VppSmaJaNtabqE32u89h/sGIbZ2ZKXLY2BeyweVI523Zwe+72c7KH8Oj1AVE7UJbU+6f/ar0rkHjW9cfzY723qxuoslcGcTw+r/qvdgMYZUSXPa/bYkG8POz/mSdrhC1JTSKbUUCm4Tg1j2BZh7jrSXJwZGggc6PcgogyvpEEDH081IdTcI2fNfeNHbr7AxDSI6AmPf2d5Zkec8WUW604S/DKyn3o9l9WcZka2r3T6h82pJbu77MNHuu/HIa4pos61p/FuNVV0XyMTIN5bCVrytHnXX8QPXnoC2pArhy6AWdsYdaflghDRZGXj11eFEOTbFwX0fH7Fnm/aU=
    username: AgCZmcaPEB4Ir67hDvlCNIlpkwyptohrDFvzgh/AwtP3TrjtCDWUyNKMSwohZ7Gqxjw3l+LWYmuZrou8BM5jcmPMnbmLWBWlyLQsxmT6sokVoCg+ydTWimK2PWVmedqYGwSZZDoKgjjjEhRedTbpO4Nj2BvMSHNqBvibOQOPGPLYzg0funfrEGfpNeF+PThhoC+z2VedYEDlbiddVDBjo7COFJI4tCqCT3pL5ULUNeFBt6fJZiRV7w3/dtTkr64W3i68/KNL72uqAS82tGlokmI6DSdFdK2BMoNOXc7oAipCdegbMAWslTUWLHAGq1TOTNUAputkvtR6b5L88LtVSKnLsaZuq7/rEIXRjvKZ5Ldx0jwuIO4y5IpRL64mNtgy0nrKbmKGekurRJ2mP6YmZi2VAC54T0yCK3xFtOkqk7nURUi+5J/eoGuFzOcaCGI812yFqDqLQhGmYwAiAXnbpPOXB8vXwFSDsUgAXG7zpGcBzLHa9oKx+agpiE6VqE8WOnaE/JxRYuIyrndlLmiJvSBc5018fMaZncd+TRYkWOgBVM83HlEWC+KOBipNWKJF0Y45kE4XIM27CjkBRoQHUrRz4RXnO0Rp0+kYCLkmPveHQ0rAqSxmgqyEjZxtr6CaHckGUWiMRumsW47HrvcS+4+T3sjupGPeoPlUVU/HFYwweVkIInb5rV/xjYe3i4/BTbCZvB0RVng=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: quick-start-build-env
    type: kubernetes.io/basic-auth

