apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: demo-tekton-build-env
spec:
  encryptedData:
    password: AgCoLSXBOLsluQl6MYFqrx19YsewM3B+CgN5FBzfiPj98WwBMpaeUHNvA3QiLQ3OCLKzDtSh0uD8GZ4zPLKHdMXihfMpPR8W2IDMYPhXsIOoaiY3uiHbAJtkgWfzHZu/0szsFgFhIevNq6PeEsBzrTLXZ9AkhdiM4K4Lka7YgB9+vM2tbczDKg/rvlLy7NK/1MSN1ZH2aOUz98m70CbKqVFXuedBHNhwmy+3bLCsBe8AhW9/Ftm15jJEx/610E9dpaSjv06oITAI6W7oH/l6C1eF+KLi9iXhlDiX9SsXfI7v2lrsYbt2Rhj2aRxdP2vXJvvuvlFUelIXtjrOzz20pnkeByE/w+y6acEtLNLB2wQwwIX5h+xivmei3Bey6NFdR4hWI1Qq0wVgskB1eWCoA670G4x2CP+ighFNbTbsJLEbKYb+L68labUWI3ld4cHWfFheXZ0ur8DPZd7QIgHXBv+ANSWiQvQADoTUuNdgxZQSzdhjAjv1+wDgIq9nzGBiKzgvhKCQXXtK7WQhreNZGcUwVSaOY2Y/bRfD2uOwNfsShDVri86Bd3+aSOPXHo9ADtMyL0E/Y/UiT8vQkorDb7lHjsYTGsUq0PmHCPviYjY86/2XwmKLcsQYGfkDILqoeaB1a0ElJ9Dz38QwwskEfpZmtdADFVXEeMDkQP0koJ8Iz45Fml8CroB1hu+pcJYUcvXy28m/5b6ojXeOXtAa4tuJrgzXzybz5zgEoX339+ax2NbKYZXfyRgcVWdDmWuO+4QpVN56gZqGeKQwjka8XSJatvR/LrMT4+/3ahsYyqTZn5MxgozZR81cb2ZCZb4=
    username: AgAa8ZcSd/aiLx2Ufdj/USuMyEpM3IM0JtwdsB2BrXB7/Z+mMK/GUUBdq6nPfLCHuX2W8xVpORawb72i3cLX4PJnMGLjE3vOhgZqh9KXV27X+A10T0ipix+0ZzHIUtRy0HMbjhqH8vlMspn+yDeYYK9vqSRZUhO1gb1FNRqcHw/lRJJq33+qA9Yowhzooj5w5lF14me2USGl9V7DGH9rW5TbELMOVqrsApgrvXTRUbJ8W8eUoGtcopCheTIhJvBBRUnNTSJ47zQfyADyNVVE37YX5vl69nzerHG+uGexiv8Np7uTFqbJwBxIqsxGdqUweEiGzmDULNmwncGOLq31RV3ObRPrj/dO1iH9Lb/+mZ2Sl5NWpDoH6KzoLXoIkqO3FqHO2yJup43Zc9uWhUA23sivnDAgWkMmWaPjvpx5SPbcH5tDwRsc4Flfx8FvwlIQpXdh3H1YkR/3xsHI59+Z3DJ6gV+6mmBI619ItiPr3BU/CHTmAIkhhu0ZnFs7cHGFu0pTLwbVmVWMIMqBYT+K+C5BtIDBZYM9PBxFeVkugRap6UnTz7Y1Q1QMsPzPf8zEdAwTybnw+Dec1VLsCutU6WQSqA2wMFCqAYy2DJ++ND4PsWBA6eUw85+UMwso7JF4LYvdHpCMskTzmzbiuyumWiBHoIC5y7WYJXN4YVRVMNKdoyEldtys8kZ2nTzm0C9185k0/Cb6dwE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: demo-tekton-build-env
    type: kubernetes.io/basic-auth

