kind: Secret
apiVersion: v1
metadata:
  name: basic-user-pass
#  namespace: demo-tekton-build-env
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"
    tekton.dev/git-0: 'https://github.com'
data:
  password: CHANGEME
  username: CHANGEME
type: kubernetes.io/basic-auth