apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: quick-start-build-env
spec:
  encryptedData:
    password: AgAB1s3cLFrFwcfg/4FaRaetTXuYb931hmwBaw6SkkmeIoKzikD+HxvUM5yD/v5kPTsIxPYYj2LctDmZL6a4PaV8+exY8Tb2FJop7l1Acja6niJxLNKZfTyMTZUkNTVWVK7zi8v4EZ7I8ZIiIU7BrTjqSlmOMMlLSUx438iX0BTIiCvYFNM7Ik9ODcysWpOqfVWZuin9QoIvcQHNcZ4IUrRmLnVL8Qq8kAh9eFNlyvlii+84n7u8vKQnmU0bVU2L7uIwRYFxhQ5UsfXPlX4vjhs02V/7Cn87WFjzbqDPOZEBuKVUrn0kkbhElHhWFaTmsNcEpu4TWqvdTlRcEiP6Cq9nVYQd0IQD41v4rUaKKZBdiwOorHFAPvhbqrrP0xX/QavENHQFpOqg56BcPT1wStUzfYhKxWISEU5fgLhEDRMbQWa42Ri+wd7F2WRH1n6me4NqMSuO2OhSuzYPzWdb/RxKbSjCk1rTuef16f8Uqnkwa4MrqOmf+Q8EnYLTnArFMNqh9JqLGzWOlx4P9xUQlyJLTS6H+T1xzzZ31SbRS2U9TaWCDieNL9R71YbxW7N/LYmy3jLJ/DzwqvCJYmieURqxbcXn6KnBWVoaTyDA6SMH8B2jLllJKzEDDFQPKvCc7SuE/xf5rdVf/LANBrxUJM/nTLJAWavSevnzcx6shvdqLPxD6WsQxZcLmPqpDBs9mcJ8JWqhLYZgee8bjE9dh08hFPWZQaWIs3k12McUQaIVPUolIfSCfMVaK0lQSp07zLrUfirFUpgR1fbOT2UYVVmHaHL+gyj7JMIss1B9b689VDiVSXetzzbp8KYTVQk=
    username: AgAtzWftM+SQgi3XWfCPYsPSWJvn2CXjkLlhnsUt6R9aWBjQ6JwKWYdFwh8vks4Yjh8E/y45MoL4FeJIfWwctb0c3s5VNN0+dCSPJ8WorixcWLcXSQPybmMgeihipt1hlqBudeb/NrUPDXkubQzTaEMi42zRdRUzLdnZ22zAYsH5i4K01RDl29zIZ32VscKyG5P8jvEqiww5B/d8kc7TGpETaFWhcB6y2lHHOVX54sNz5Deai/IpqauvdvdqtQRpy5hCEb51CgI+3HFGeib6k0Z28k09zqPz+cIDzS1rbNSZ/KoxXxk7VmZD7ZPDJHKGIRbqbNn468r0HCRRIJYRtJFq/sdyCtVIR36KtsrmpSB4bJHEGAPWBTIWhC5L6MsnmooM9HVb63Oe3K6GRUla4Z8ydh0AP7TSKG4YfYP7IVqQUtlAYC8Eqm/aMWtRrUhrdeRho32jjeWd9aoVgereu92ua5sN5IHThwyc4FoL3ue1NCqO6KtlGNaoNq1SMVkhbGYovD/Pu/A8w4cuZ78J7QIht7YdJrdQaK82/b8TjKscuK8j2gXpyRKKPanBtv+4mau55U3f4hQnX7QNy/SvprHdhvghFtvBprt79ndBknV4J4cZy4fitxAR3yDl6P8MFjNG7L7f2obdyBAfU6fKcqMaeIi2q+ysMIbuyHHZu7k/SuUOwPmkMF12OBuA7bX4SlhXo76ePZc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: quick-start-build-env
    type: kubernetes.io/basic-auth

