apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: default
spec:
  encryptedData:
    password: AgC17WHARLBaQPtWADrNhSHBGPlqGLzd5FwxOXNTRRdCycPI0gKFdepwKs+kjhzZjUyryGcr53bxYaMZAeglIRvXpbTM1EG+qyJgJK/EXyZ/o46G2qP/WTbgHVX2rfNiDVAb3rwwAV+p7E/Xv/qoB4WZqwMEuzWMjzDazAtHmeTqaWv9Nd5ne7vfuM3QPVD5s6UNF+tsCmVfAK6tnIVD+JIhPm/5bspcNp7f5C9jpJCsHUkXvogYJrodUWLdcot71uHomPs73tyWcNSjGDy3Yv8VYnxCWwx70tJjIE0VhuR3M6ZBPnYwFgm3sNMgT8OH331y70CDIwoe3e5cpaH600LVr+nG3wqNHN2tCSct3gb+ixaFsl7SessY62rDzjGh5i8RgIK/1I/uzSPrPg+p5OUWX2wEseyd8AG2e5v8A7yDRYljFCb/pctXEeN/+VbKx3soxRRtm9Z0pGJXL3rzm0r68W6hHFExX7SHB/dApfXYP8T5rkVuDio5cpqkkVzE2DMFIlWBPIl7qX9ZOXSD4jmA/yWTfb8nBxT4yxcOWaa9maoz90oduDD/7TLR6OzG1qZ1KH9ujdm4YAUdSQxTU1lz76LjQtHXva7fBsO9mn2U+bTxsvSoxRJny5LtcZbiU++Qz0Fd/tLN1UAgDzHJl0xs3i4s7YznuRNfA3Sq7eBdbsVarw81rLhsC8nnucLMKM6AK9bAEMYwBRVQ5BmaHVcEMngCTa1IAxY2aOFcxdo8lh8aqXo+0DUNq6ATShJUxlMdAc0oRqJsHnE8GyIQ5Vejz2ZJWvHDsa75gyz9kOxyxc023E6JuDIVAMy7UL0=
    username: AgA9AcFzmY0YkH8VgzluYYVRxsodvqqoLUFBrMtNTSaZVB6Qm/gEXvL0kYxd2hRujmjVtKr27L6uJ0b9vqifFbfZO4XEvBQuTXr8b65G3WIHpZpgceuER+5OdbuIR1o8nC9kIOgBPbMWMbBllD3UFuRd6aykWqmK4L9YdYHsQZ3Ltyd+HnrlHBMQ7ScgdEeG8nVPgikjacVEqZQiuBWXSO+PDvXpNuCKagwouBiLRgfB1oNyiUv943MKj/FHEMgeSJh1w6D7uL+u1ZneDGE9HnUQ1YLbNeFTL3lxk7ZaDXI8yV6S0senERbBY07hW7t7ntsf0G2r6caNPw0S29OqfCXxaskavjXXK+v9aiXyVk1P2FYW9NyBxL2jgdr1HpQcNRmtVyd3cVATNnZyqxuBTmGK0L68L372iY1WeeXqbHQTAVVZXmotAoGuhce63AFpsHwf8YT/BJVHrcxG4XoHEfRkp7l20P5c+S9zRkYtf4p4qFEOayAXzvwzKceyrMMDnvJDvxaVUJ9Y3pHJmltV4kCGSC1W4kYxzfqU75H4ss+70oomBYRBzKH5PlDOHnjlI7Kid2d9Jam9rDgN2AwS+82nMVyO81ewJdk1Wa9wgpZnh0w/xaI/PS6HH3cJU0Y05VgFrdWqYd8tGi6TxVMM8p7X/eHPVyQ2vyisivG/D7B1Ewr+plmav+s+7JtUasTG+pG4fGmifzg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: default
    type: kubernetes.io/basic-auth

