apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: store-demo-test
spec:
  encryptedData:
    password: AgDE3ZWD0KF3kOTUCBVf069UnVLnfQUCHcY3nErh6doJfGRTK8bbvBHIayK74rV9UOU5GByQYpvJe23qFaC211HuCx0ciJpT+XxdOa9sxlta1s5KeV2nuRmTxmnEE5ziqs1qi5r3xnYjSbMNYo2a6dibkExo5q6plx26q6C+lowNvX7sd6kgSRna4LOQQ94WOHFnAmDHfS0Md71rM4G4xfkw3YUa+wJlo3OVuZCNOjcj/xtHvFBqzSBOefyAFhoZYRs6PnkgBrfb0VcanCaztlpQzMLTif0BwZDBZ0vXk7yNrVKbx+zpypq/z9FnKaDYpCylONYaOdtAfpLy2aixe0eDAYrixAjwuYwUEe/Pf+Out+lhMN1erUdLQmA5Ji+k3e3SH/vgIr33ZGifX+sdC99GwhXWIdHttsv2B1pv5QgHCm8c6GlMfZBeud3+fzBuNq9FdlF4lT3DTr0n/3JHLqlivbQ9m1Y7xY1NIlLasvRt/5rKscSOEkvNKx2ndIaDRDoIUPi5LpA7GPEll+5W2ajliLSXf5W0HbkkwHT67KB3/gzwfkxLpHqPESAwD7H8XvnlAVbFPY5rRAcjaTcc1jWtG935A4aRBZz3ykma66KarrxF9x6HCfgzWKXXa86O38FE0Y346HgttJKBvG8VyL5j9nsPkWNSm/vMjfIXt3k9HCBdW8K/Mx3yXIOJJBwM5+UAP5P+k7WrYd5/1KmSJpxPZUH17XDzQG6qOcjpywL+ndh8sjZEqnPEdDxLiY54noW/1TJa6P/zz/rPnm5leyUWuuOavlxG2AaWznZ1luAcRPVYMgLL57ToMmewLnI=
    username: AgCTyxFZw4u3x42zS3kc2FAinIguGy7PeOoq3g7+g3VG85I+isG/Yb7I71jD37Kp0IABQJop0W7KpLnPebu1yAic172Ji8jnTy5clVfKgReYtUdbuPrnx5FR8nhVgz3oF5Kj4jGEwCNPZCaR4bvWyXdFbcXDUj0vR5+4GXD50pApE00m6LVZ+V7gWmVNreBTVIpqBzjIsfT/vL1GXoAI3s8VlY0JF/j1KWzpfljCKhsh8AjlydGCvJwi57CL24hdBeJcx6wNYd/UUJm+fga4eFLPwboY1DWLGZcPaqiRNaph2JtzNJ4IwtibjRm4E585+qpgia1yUIF8VxaBBRJBMsjhrKKU1wDs+MD/lGGjv0zy2VN/SVKLB7mRVa8KJNFUlp5nRHA04f6ljP8djN1X46EeW+XVUyY5pE9Sfv5oApLScwi3F/Tf92v5+Eyfx+NfjPPYpS1W8hjduEGvH9tp2TykGcFyJGw9TAN8NePUySVPHcpxF2VvcnMhhyOEqABQM+kGhNNCekZhIXQ1ondUvXK0sSk5nvSJTlMioNdgF/mC7bzY7jd82PxPgoXJuWayTF0PCAKjwGiJfmU6sPEKs9xIMj3vlUJmMr4WLHYXsLqSBSDaaUeEr8KcFBx1umvTxl+3Q+W1LJDCGoTDKBnygvUdHyNbc4zkGAkIWfgAvIDJ+z+NDk7NoyWfLrod5nXqozqhdHGT+e0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: store-demo-test
    type: kubernetes.io/basic-auth

