apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: demo-tekton-build-env
spec:
  encryptedData:
    password: AgALiutYWOSDZ4gpNOrICsos3YGH+NM4Nx7qgPAir7nLYEYdSOiyTCfzGcJS690Og3SjQOLW5P4dXwx7Wz3AQBnUWgxF2KTdjnnqX2YSI8W19xpwnuNLZ4NCgwxjZUF6Q+tY2zf/pIlXtgUqupvj376BJaxNhNyUVfWc+aAJBGENVHsrUg+E4Ytl1EIVwEk7w7N3MGPaZcWD5t6l/dLfZ1bLzVUwtouRuCdvfl1EbABTxLr4R5uWBgqojd/ILd3SQEAslFICmR/w0zUGNKfTq7v7y1zMDaw/7DFKLuUjbl7V1DH1qFlqre7MXTBXzVfqovKkBWLoTFgcroJ34iqauI0t0iIQPrJDCBOEYqWGAejiUvy8s9lo+nFvcynAMiO6K5bxbXvku9eSz3TIBTjhnURykdv/K2eFnG+spjOwxD88Wn3P1T8QgUzZeIcvyvXL9UkbIkSr5rYdCwlho11eQLCeqYi9268QT1sLoOBddB9r25wOuMIGgN6k72ZDOxdkDJKAn+HKO5EOSoa6ayx4ZRutODemr4JPCiVutgWVVjecMQ/AHtoZCcASxUqGSzmSQqmDDJQFD9WjSowAsh2j5PyFgQCBrrINBScSmksLYUDMEno7U5XUWYR9rHIWe9/skq6QVD/Mhw0Ww2ca6pvOHnBDEKms5ok8VP0iauPAylnIz5m1dO2/oj65P7pBbs7W5+5Ao1CebvBPSFG87LdkpUqeGKikdof7+Xl8VOt/Y1vzXLU9P9fB5XHMhq/8AIlilaoFXl1vBM6Zsh6JTxtLKdw/Vek7sO3r8YDzTrNCIAyaF4fxtIMNZlqteApjfEI=
    username: AgAk0wiPmrH5/GmeeBIqjL1vbCTa0hyxRD88TpyfiEuiKUG4RZceY5xE/C5kqSMqd7Qx22BWdMmbXA0WGpnP52xhLApi1wlnJFZHVvntZPoB2AHn+JELoesZNHU5lZWOI4kPnOauwypVtfYVPOE7V4X5GzFWVWS3LC9C/VbnGk9wkMyo4lLtEuN2Sb96r1JI2ermDu3JOQHmqmh9Y5aBvw3ypTbmS4UvxENWOxkNFUXaLkDw4ENq64xii/pcYnMVhSizZC+B9BcbJoaKh6/L9fR3G/p6TxrZIVqHFRwpPcCvbAmqLp8GISkKo4fSABgxHQFznPWZHX8qJ/X0rLNTLCvhNmEnYV5YYzXQZ60r88RPdH21N9E27BjXINjfJvwDB4usMTRkvbUAmaSBian9bwtWOwWnerj0EtFSScBaUX84IfjPoLc17KmGhCv2ChdwUKiSwcmLe3MDmrlnwYJKI+HdkG8tKTUMC93/RfThBDwvwNFtpCmCNDcH6kGbQARKvsk8WzNmW1pwtlsMLzEAEzWpopr8HguF21/BwDxhkfag+OODes6y4Ii8myDLLwDNn8hOK97L8wCgP8MhsVqLNNm9zNhPjKlaLXKxlc4OhzL6dZgx1vgOAKlfmt5G/WFs/Ppd3Hc0rC4eNEcjQtVe6jylcQW3KKFf5EqW+w+/UAImIxgMRaFSGL6gwPHGjLH3O9d1E6vi5IQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: demo-tekton-build-env
    type: kubernetes.io/basic-auth

