apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: quick-start-build-env
spec:
  encryptedData:
    password: AgC4x3CGOTuTO9d0jCFi8eQVsXCHSeMCWR+WG/47va5heCMhRjp1gwJFaC9VKQNmyjrqgB3chtgmGq2+kB3eStrmuC8sFeK6VtMY7+INK9iHxVpgeQCwG7nHiCpgRVQVCWB1A09Sz2UGEuitlXxh6WFMVIEsOkR4wBPKfk1fAMqUumgxpLk4t83hpCpzSFQ5Il/nrV0xqY/jTsURz5xHYeCme/BLd73aF5nK/ZCCTzyc7KE2+TRCwkhYzyfkrJErh++r6T3ZMdg+zgcL/7hNkVI56uAUqwuQdUFmUyVzzpvkJKC04+RFxWtu/RBbqbBWrmYV3+ZGyCFaO8CmP6ZMsGGVLVGgRsW5UD2oCgTquyDnuBNhlhVTMZRPlhQMU9MLljxZxntzxATe9s501vX3hcJ9y/UeJ4AVWujmorhzAHDSYjxK8MLUuyYD6x54VjahE7JOPGSbagB4MSPiVgU2fviA/4iPtzEPG1ki0mQdVkeMVD9YMjqKO3cyZtKtwZiIXUE7dQKwCE5P5PlrPl8+9SqhGruOrMD8wYa/BrS9dIwfi0bFHbYX9JmgwLJp8KYHGHtFsWk8YWgaI0tnmJbD2zointvNfGA3Q40oShlsgjxfBaV2I1BRzhUGjhqlV/a7PYkN2fgszd4k0Zmd+7rIWZf3OmGg3VLGOLxU1cjDubSwQePufLYV62TcH5rOrt9mG10XsQGT6c0NvElaxYtKdk94dFY3LZyUI9hZkNZIplN2D4XG2ucb3NewZ0RDxR9oQ0FWg959AkKvesSMU41+gpJ9jefN7m2HAKrEVygZpDLWz4Q0QKBSFtdFsMn0dxU=
    username: AgDKYnedDRk2G1t6i+qkcteTFi+mmykEQzJbBhdh9iTDU08q0Sso/8OEOPoNhpoX71vsVGvq6fJ1ija9BIIpF1AW+hSByspxYD6Q6XsFpOaoteOk+Ec9DzWlZb7u8MkROFVRmG7gWhZOF38HWLhsBMybhz0LI9mDc92Pbi3AAewhj5plGE/AEdNe7UKgBs1Gs4l2LpnjCTrg9SNHVCfI15VC5cfzOlxZvAIkeWbMdBNmd0tgR7EkLp8Nr8c2F+2/b0RF4cdqZnuRACfAVh8nKcsibyi4n1CHiytMjhVni7+M+/SAFdGp1rv6mFFr91gGBDyUvTgYL+EBdwFt3BJF7oko7iIZ5RZyvrlyaD1KPNbt3e3L5D2NFrOZj3fqk4e/VIVYdxS8J95/3B+HdvOUKSlDMO5iDRzNSuSlI02Zo9tQOjWQDKKFV9d2xbWwlLhD//3OainGyXZjek1oCvQnnAwzlkW/EpvkkdaxWQDcw/mdumKKTx/v0vN559xmJdLAoTxgBtp7kT1QYBOoa+L9CoVD6NdiDkwg/jspYPi+7lL0auGEmbMh+2JsMbWwrcEL9ur33d3oq7/ER6CdxrPkws+JQa7sSuhuiCNQhtwtjQhJkjTXxxozQZuba2EtqQoXfh/OX36Rj/RCg5twgA7HCC4x82t+yq3pMsuPQ8ZsM+iPB5rXqTafnHBghhB2f5o/fBuzdZklZGU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: quick-start-build-env
    type: kubernetes.io/basic-auth

