apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: quick-start-build-env
spec:
  encryptedData:
    password: AgBOMU42Et1r6MUOd2ySeku8xcZXnNFe2l6LV16g+YQBnyOv6IP718aFFHHV1fVBxntRWg8C4Eno+LAI1i+OcKCOV2bBq3Foq7BqWYIhWsaZNeAT48ifpIK4Kue7iniQd/O82E29IpmBLI/29RiFZ58rzGYFCARJFsxeWu6gx93F406GbDmOtvUvwfBTZ5pSYB7Xjm9BXhOE7Us5YD1f8aWSzOl3pNDYVzlOMBiM7ygWDOe1y78aTQHlqWBRrNDHKFDENOw830IDQRhB3GKLgovvdwr+WEd20lnhELsb7Jy8Spk2k994XBoZ8ynf8rdcyXgNz3sN5FL4Tr0shmnSh4I6TKOhbdB4Ti3ynileoswok6TY8WujvdkaD399kmJa26iIun1l+dySw7AX8cmMSjLNXYiarUhIOeRNls+NOLw6u3op3drnVbqYrAwP09G5QV34yruLjhEj2Pn6E4iMTEYOOFhuCklOUgDaNmXfi9CL0gOfyeOqrXCeLjeHvP6MV+FMAF/Gg86whyAW+sRou+iTgx51gdwysuYMGYH0ch4ssSiEohLwnhc6HM27feCLU92BCPdX0Dhozd4E929zOn6eFXfp/se07A9FIIVf3Y04XjEozBtR95OzSDIuei25heDAHsRX18Leyt/gDe1hs8UJPwvsZedQw7cb4uJCZ3ndmcTdPVZebbk17OjjzOE6MJq53OQ6WjFdsEnHJhwLgHgk6ewSZbkStNlhi5J53gFJ8zlQS+9n8DvwVLEPKGd/57WJY+MIM8mdSrRZFusl7zEh2LNtWe0J3vc1tVvprQC6Fj7kJ9D2QqDsS2n92Jk=
    username: AgB1cvStd+iM0AWbvlKg7UQR/IyWIlcBixs6IQXM37AwxYEf581QfVlBdiIGrL0Q/hXBTLCrtc6BCpo9h/85indoAnIiaFg1bO0rFi7tntNG9P9SM9RfB78jKZ4NzbXFSyqubwqJ6cErFygrimN2LX/g9FqHjZviYiqXB3nCBLjZ3L+7zVDl4kOCsdbr3OFOV+s587MR1MwahUUxSRIViiCLApc+560ssxE9GePZRTOUfa5GCgX7pFTJ4l/sJPfGSm0paRi/zVhLGGC0Jm6BOdXAygxxLBdIhh/kD9n9eL5vbj/AogfepOwWngXesrsAxLgyiduIJAs5ANZwigPGhHPRVtkwyNspuw1RpWA2d8/VrLBpR+qTr9gnQZJM7oT1XWBO+gjnAHSWER50/JvxSuzD2Hxp9DdBpKNwv2e4xCT0agdD5+SxtN+6RJa+QikCxHBwqwPorqeKpBML7Bm9FW96Y0eQTeSz7QNkxYkzqMAye3AbTx6Ajg21H0kZ3LqToq9DjIFPVoWuczRl0S2hS77CfdnEB6+DAeEEFGXUi3V8DmgxBIlqFLZwNhnw4OOdJtpOQTTvIMXvi0v6HVYkV17ShpaGnr1K5NNGb1VnMNgpNjEyCBwPqSPJZ4DeKKnYDs/AWgbSxG58gHBxOxl6DXenZAAIhiUliaqlAdh3PDSp4rRz/IZ6B+VkBJbBaEz8od9PhRKX6Oc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: quick-start-build-env
    type: kubernetes.io/basic-auth

