---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: basic-user-pass
  namespace: store-demo-test
spec:
  encryptedData:
    password: AgBLrU/z+GsDq/yGU0aqIxPewVuWCYfcVQJ26fa8OdKSkXZnJwK3DXxG2JGBZibud93QuPLqX1j+DYbB+/lyfM4IvX0e+YLMylRUl+yCLEgR/Ud4oclxkKRPT9QP9FWjLUY69o+KXZ2sgl7v216lvABu1uSROJ44zGV1pogwigEYrwHV0dRBOljPxt6EG1y1kSj/F+ZOIWR8vM1WXXBEccCXYaJ82nI4HR8uhAxvauvkOjhbi7EU3ArAh4AKCt+4rYNCVVXWGYjNGN2SWbnjUz0xdJvDgVFIi0I7TQXYCA4y1qAMjVS5rvluxLF6KHcvuzmMh2JNTzd0/T1ZUhiR32SqJyL6lkDoFGyFspvpuO7ysJCjK6+Erm02j/qTmxXGnr8XbrJ8z6JdWxWK2GT7WYxH5iiHYjVUx955DZDSDznf0X9Y58f8QeaXQEKoubzHWqE4TASN1TJS2mI5F2fOoO5rbeoIa4eYYiCIWbxqmGs+zAbm6DIZSw8yJvhrAi4cbY7zdIdoV7M6ry13d7QWolNALHkA/jHkQseiiwQt0VYC6PXGDFGOqWzZWFVJVDBWaZT9E+A2gIPjW2eV4MOb1rmh+CEAVike9bUwj5lEca0KpKVOF0FM8PX3tBRohZ1Nqo31uIEnM6OBCjICQ3LE3BOdM9gDnSaqeSVci+St389dPFL6JFgFotuEX8hwArsbMxinC8QFoV3pz0zBXzqo5AYAp5yvZolEul4Arb8RlpiE9khnhzYEWXpjssFF9uhpyggHN5lODYJ6oUVW5BoihM6+Kt3FPmoMXQy/+MsZ9ZeF8vqK7B/8n0w4tvKRP7A=
    username: AgArkqYpnDkt8J7M4EMOXj5ZxU+kAHL9qBFlvjmkIfQVyjdy2nRb87suyw11U6h1AnODT7SoxGteCK0Vb4NbhF6gr5zSyQlwDryPtGj3JRirehS5rvgcN8+wC0C4+6XDxQczHHvmLfD1AgEzX/4UEBRjwGQYzvLvDn1cLRAKV3E70TVPQ8kzSG8DiyfHElYK0zjqrbTtiSqWohYdhOvaIT5HhIwvbWrSUycNtweoqsQGpJI25MAcQkK/nGspAG8QsZLYu/eZzk4Op56M80OLjCOtKv3I7u9J8sz+YqBaZJoo0tVMARxhhaa8hC9FHOOqz6XB36qRaALEQz4uAh4ehdQUHojQBoDp0bsf9OYR+wwJHXHIU/4704paPYGsuTF7CwxZVRG3J3J8HIFsIWXXB7GZqbyUhHC9u+JqnuuVZSFQlfHCFovI3ixwnDcgQ7yYcXP2V3XIVv59IeMwciTuUDsdNoNGAeKKzLP6zduGnxI1MvaLivTdU+JmjsCAprUX9Lo2JI3sjoRTVQISTO7FAzp5s8hxXp/FA38r48ZQDYXGyDkogtYIRKZ3Ub7M0bUbivvGupr/gpalUv7vN4qwcp2a5I/y9lkC7nV33NwafhGA7nPGm2sDiqUU0LYG9cF8Hn16g7JciyGSejauL/EcNQ6Mj0b6NMfTnZSJ72p3mWph0mJnj1GNeb9cDTXEd2r+FxqMv5rrrDY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: basic-user-pass
      namespace: store-demo-test
    type: kubernetes.io/basic-auth
