apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:finally': {}
          'f:params': {}
          'f:resources': {}
          'f:tasks': {}
          'f:workspaces': {}
  name: quarkus-getting-started-pipeline
  namespace: demo-ci-cd
spec:
  params:
    - default: prova
      description: Tag dell'immagine
      name: IMAGE_TAG
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/mcombi/my-quarkus-quick-start.git'
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:bc551c776fb3d0fcc6cfd6d8dc9f0030de012cb9516fac42b1da75e6771001d9
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: maven
      params:
        - name: MAVEN_IMAGE
          value: >-
            gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
        - name: GOALS
          value:
            - test-compile
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: source
    - name: s2i-java
      params:
        - name: VERSION
          value: openjdk-11-ubi8
        - name: PATH_CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: MAVEN_CLEAR_REPO
          value: 'false'
        - name: IMAGE
          value: quay.io/mcombi/quarkus-getting-started
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:99cae35f40c7ec050fed3765b2b27e0b8bbea2aa2da7c16408e2ca13c60ff8ee
      runAfter:
        - maven
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: source
    - name: s2i-java-11-custom
      params:
        - name: PATH_CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: MAVEN_CLEAR_REPO
          value: 'false'
        - name: IMAGE_NAME
          value: quay.io/mcombi/quarkus-getting-started
      runAfter:
        - maven
      taskRef:
        kind: Task
        name: s2i-java-11-custom
      workspaces:
        - name: source
          workspace: source
  workspaces:
    - name: source
