apiVersion: tekton.dev/v1beta1
kind: Pipeline
***REMOVED***
  name: quarkus-getting-started-pipeline
  namespace: demo-ci-cd
***REMOVED***
    argocd.argoproj.io/sync-wave: "2"
spec:
  params:
    - default: prova
      description: Tag dell'immagine
      name: IMAGE_TAG
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/mcombi/my-quarkus-quick-start.git'
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:bc551c776fb3d0fcc6cfd6d8dc9f0030de012cb9516fac42b1da75e6771001d9
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: maven
      params:
        - name: MAVEN_IMAGE
          value: >-
            gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
        - name: GOALS
          value:
            - test-compile
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: source
    - name: s2i-java-11-custom
      params:
        - name: PATH_CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: MAVEN_CLEAR_REPO
          value: 'false'
        - name: IMAGE_NAME
          value: quay.io/mcombi/quarkus-getting-started
        - name: IMAGE_TAG
          value: $(tasks.git-clone.results.commit)
      runAfter:
        - maven
      taskRef:
        kind: Task
        name: s2i-java-11-custom
      workspaces:
        - name: source
          workspace: source
  workspaces:
    - name: source
      persistent

