apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-volume-pvc
  namespace: demo-ci-cd-test
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi