kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tekton-build-ci-cd-pvc
  namespace: demo-ci-cd-test
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi

  storageClassName: gp2
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 7Gi