apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-build-volume-pvc-test
  namespace: demo-ci-cd-test
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: slow
  resources:
    requests:
      storage: 5Gi

