apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-build-test
  labels:
    demo-devops/app: build
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany