apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-ci-cd-test-pvc
  namespace: demo-ci-cd-test
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi