apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: quick-start-route
  labels:
   {{- include "quick-start-app.labels" . | nindent 4 }}
    app: quick-start
    app.kubernetes.io/instance: quick-start
spec:
  to:
    kind: Service
    name: quick-start
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None