***REMOVED***
kind: Service
***REMOVED***
  name: {{ include "quick-start-app.fullname" . }}
***REMOVED***
    {{- include "quick-start-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "quick-start-app.selectorLabels" . | nindent 4 }}
