apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
***REMOVED***
  name: quick-start
***REMOVED***
    argocd.argoproj.io/sync-wave: "4"
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.url)
    - name: git-repo-name
      value: $(body.repository.name)
    - name: git-revision
      value: $(body.head_commit.id)