apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: demo-tekton-build-env
  namespace: demo-tekton-build-env
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - demo-tekton-build-env
---
apiVersion: v1
kind: Namespace
metadata:
  name: ggithubcom-mcombi-my-quarkus-quick-start-config-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  name: ggithubcom-mcombi-my-quarkus-quick-start-config
  namespace: ggithubcom-mcombi-my-quarkus-quick-start-config-ns
spec:
  type: Git
  pathname: 'https://github.com/mcombi/my-quarkus-quick-start-config'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: tekton/overlays/classic
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: demo-tekton-build-env
  name: demo-tekton-build-env-subscription-1
  namespace: demo-tekton-build-env
spec:
  channel: ggithubcom-mcombi-my-quarkus-quick-start-config-ns/ggithubcom-mcombi-my-quarkus-quick-start-config
  placement:
    placementRef:
      kind: PlacementRule
      name: demo-tekton-build-env-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: demo-tekton-build-env
  name: demo-tekton-build-env-placement-1
  namespace: demo-tekton-build-env
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
