apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-tekton-build-env
resources:
  - pipeline.yaml
  - s2i-task.yaml
  - storage-class.yaml
  - pvc.yaml
  #- pv.yaml
  - quay-secret.yaml
  #- build-service-account.yaml
  - github-service-account.yaml
  - update-config-version-task-test.yaml
#  - update-config-version-task.yaml
#  - triggers/trigger-template.yaml
#  - triggers/trigger-binding.yaml
#  - triggers/trigger.yaml
#  - triggers/github-quay-secret.yaml
#  - triggers/event-listener.yaml
#  - triggers/route.yaml

  - promote-pipeline.yaml
  - promote-task.yaml
  - promote-pipeline-run.yaml
