apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-tekton-build-env
resources:
  - pipeline.yaml
  - s2i-task.yaml
  - pvc.yaml
  #- pv.yaml
  - secret.yaml
  - service-account.yaml
  - update-config-version-task.yaml
