apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-build-volume-test
 # namespace: demo-tekton-build-env
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  nfs:
    path: /tmp
    server: 172.17.0.2