apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: my-gp2