kind: StorageClass
apiVersion: storage.k8s.io/v1
***REMOVED***
  name: my-gp2-immediate
***REMOVED***
    argocd.argoproj.io/sync-wave: "0"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
