kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-gp2-immediate
  annotations:
    argocd.argoproj.io/sync-wave: "0"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
