kind: Secret
apiVersion: v1
metadata:
  name: basic-user-pass
  namespace: demo-tekton-build-env
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    tekton.dev/git-0: 'https://github.com'
data:
  password: Z2hwX0pqZkw1Q1k5cVNZb2NVd2hCeWdncmROTzBNNHdBdjA2UHNWNA==
  username: bWNvbWJp
type: kubernetes.io/basic-auth